language: android

sudo: required

android:
  components:
    - android-22
    - build-tools-22.0.1
    - platform-tools
    - tools
#    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
#    - addon-google_apis-google-19
#branches:
#  only:
#    - master
